# Generated by Django 4.2 on 2023-04-14 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
