# Generated by Django 4.2 on 2023-04-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_record_alter_review_owner_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_text',
            field=models.CharField(default=0, max_length=250),
        ),
    ]
