# Generated by Django 4.2 on 2023-04-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_record_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='album',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='artist',
            field=models.CharField(max_length=100),
        ),
    ]
